### ISSUE TITLE
Height of image start to change after adding onScroll

### ISSUE THREAD

**Issue by nicklaunches** [oblador/react-native-parallax#11]
Doesn't matter what Im function im adding into <Parallax.ScrollView onScroll={() => {}}> with every row image height becoming less and less

```
<Parallax.ScrollView
    style={styles.scrollView}
    onScroll={() => console.log(123)}
>
          {DATA.map((story, i) => (
            <Parallax.Image
              onPress={() => this.goToArticle(story)}
              key={i}
              style={styles.image}
              overlayStyle={styles.overlay}
              source={{ uri: IMAGE_URI_PREFIX }}
              parallaxFactor={PARALLAX_FACTOR}
            >
              <Text style={styles.title}>{story.title}</Text>
            </Parallax.Image>
          ))}
          </Parallax.ScrollView>
```

```
var IMAGE_WIDTH = Dimensions.get('window').width;
var IMAGE_HEIGHT = IMAGE_WIDTH / 2;
```

But if Im removing onScroll everything becoming perfect

![screen shot 2015-12-10 at 10 58 31 pm](https://cloud.githubusercontent.com/assets/1409277/11737801/b1e0975e-9f91-11e5-8d83-e623fda33800.png)
![screen shot 2015-12-10 at 10 58 38 pm](https://cloud.githubusercontent.com/assets/1409277/11737802/b1e6e87a-9f91-11e5-8eb1-8b8ed051405b.png)
![screen shot 2015-12-10 at 10 58 45 pm](https://cloud.githubusercontent.com/assets/1409277/11737803/b1e90768-9f91-11e5-8e4b-404a1a2254d2.png)

**Comment by oblador** [comment]
Hi, the `Parallax.ScrollView` needs the `onScroll` callback to animate the images. When you override it the images wont get animated :-/

I can add support for bubbling the event upwards but that would remove support for future optimizations of `Animated` to be run in a native prioritized thread.
