### ISSUE TITLE
How to vertically-align images to top?

### ISSUE THREAD

**Issue by schmoove** [oblador/react-native-parallax#12]
I've tried a few style tweaks but can't figure it out (quite new to RN) - how would you vertically-align the images to the top, rather than centered as they are by default?

**Comment by oblador** [comment]
Hi @schmoove, this package currently does not support aligning to top because that would require the image to be the first element in the scroll view. This component might be what you're looking for: https://github.com/lelandrichardson/react-native-parallax-view
