### ISSUE TITLE
sometimes glitchy on iOS (lost frames, space between images)

### ISSUE THREAD

**Issue by faceyspacey** [oblador/react-native-parallax#15]
sometimes the area between parallax images show, especially in the simulator. And sometimes frames are lost and it "catches" while scrolling. Are there any known performance tweaks we can make or should be aware of? I'm trying to get it buttery smooth--it has potential, but it's not quite there yet. I'm hoping I'm simply missing something.

**Comment by oblador** [comment]
Hi, scroll events are throttled and sometimes out of sync. I'm afraid that until Animated transitions are moved to native they will never be 100% buttery smooth. This is a work in progress by the exponent team, but only for android so far and with no known ETA.

**Comment by faceyspacey** [comment]
Do you have any tips for how I can optimize this package's js for performance on iOS? Perhaps even objective C things I could do.

**Comment by faceyspacey** [comment]
I see you stopped using `setNativeProps`--are animated values using state faster? My guess would be _no_ since you are using `state`, which because of the react update lifecycle isn't as direct of a path to the native implementation. Please correct me if I'm wrong. I'm willing to put time into make improvements to your amazing plugin here.

**Comment by oblador** [comment]
`Animated` uses `setNativeProps` under the hood so there shouldn't be any performance difference. If you have the chops and time, what's really the issue is that `Animated` should be implemented natively. Check out this branch for inspiration: https://github.com/exponentjs/react-native/commits/offload_animated_jan_22_rebase

**Comment by faceyspacey** [comment]
that might be beyond what I can do. ..so basically you think that the component state updating lifecycle adds very little performance overhead? Currently you have to update the state before every frame, which requires React to diff and update the virtual dom on every frame. I know React is fast, but we're talking every frame of an animation. Don't you think skipping that would give us some noticeable performance improvements?

**Comment by faceyspacey** [comment]
Wait, I think I misunderstood. Only the `offset` is stored in state, which only changes every once in a while, whereas the `scrollY` animated value is wired in more natively so that `Animated.Image` receives its value without the need for react state (triggered by the scroll component's `onScroll` handler). 

Am I getting this now?

**Comment by oblador** [comment]
Offset is only set on layout which basically should only happen once unless you change styling etc. The rest is never touching state and moved by performant `translateY`. Problem is the scroll callback.
