### ISSUE TITLE
Warning: ParallaxScrollViewComposition

### ISSUE THREAD

**Issue by vedovato** [oblador/react-native-parallax#19]
Hey, i'm facing this issue when implementing your package the very same way as said in the examples folder but i'm also seeing the warning below. How do i fix it since it IS setting the ref?

`Warning: ParallaxScrollViewComposition:`ref`is not a prop. Trying to access it will result in`undefined`being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)`

That's the code i'm implementing. [Pasted whole document in this link](http://pastebin.com/K5Vfjyn7) and a screenshot (to simplify) below:

**Warning:**
![Warning](https://res.cloudinary.com/sindicond/image/upload/v1470926246/Screen_Shot_2016-08-11_at_11.13.52_AM_lnr5hx.png)

**Code:**
![Implementation](https://res.cloudinary.com/sindicond/image/upload/v1470926270/Screen_Shot_2016-08-11_at_11.37.34_AM_mxhqwq.png)

I appreciate your time, thank you!

**Comment by huchenme** [comment]
same here

**Comment by vedovato** [comment]
I made a fork of it and managed to make it work without this issue, @huchenme. You can refer this url in your package.json.

https://github.com/vedovato/react-native-parallax

**Comment by vedovato** [comment]
Well, no response. Let's close it since i made it by myself and referenced above
