### ISSUE TITLE
Use the library with listview

### ISSUE THREAD

**Issue by carlyeah** [oblador/react-native-parallax#2]
Im trying to use the library, but parallax is not showing in my example. 

Im using a listview

```
<ListView
                dataSource={this.state.dataSource}
                renderRow={this.renderRow}
                style={Styles.listView}
                />
```

And in in the renderRow method, I have this

```
<Parallax.Image
                    parallaxFactor={PARALLAX_FACTOR}
                    style={{ height: 90 }}
                    scrollY={this.state.parallaxScrollY}
                    source={{ uri: "http://loremflickr.com/1200/990/" + SECTIONS[random].keyword}}
                    >
                    <View style={Styles.container}>
                      .........
                    </View>
                </Parallax.Image>
```

The effect Im getting is this. No movement, just showed it misplaced, like the parallax was just applied without scrolling.

Any help?
Thanks!
<img width="311" alt="screen shot 2015-08-02 at 9 51 33 pm" src="https://cloud.githubusercontent.com/assets/1739717/9029923/baadae90-3960-11e5-9a09-2bff73531204.png">

**Comment by oblador** [comment]
You need to add `scrollEventThrottle={16}` and `onScroll={this.onParallaxScroll}` to your ListView.
