### ISSUE TITLE
Error: Passed properties: {"translateY":0"extrapolate":"clamp"}

### ISSUE THREAD

**Issue by kri-yor** [oblador/react-native-parallax#25]
Hello,
I am trying to run the simple Usage example on the first page, but I got this error: 
You must specify exactly one property per transform object. Passed properties: {"translateY":0"extrapolate":"clamp"}

I got this error when I tried to run the full example too. And I just can't seem to resolve it. 

If you have time please assist me !
Version:
react-native-cli: 2.0.1
react-native: 0.42.3
Code: 
```
import React from 'react';
import {
  Text
} from 'react-native';

import Parallax from 'react-native-parallax';

const Example = React.createClass({
    render() {
    return (
      <Parallax.ScrollView>
        <Parallax.Image
          style={{ height: 200 }}
          overlayStyle={{ backgroundColor: 'rgba(0,0,0,0.3)'}}
          source={require('../assets/mainImages/2.png')}
        >
          <Text>This is optional overlay content</Text>
        </Parallax.Image>
      </Parallax.ScrollView>
    );
  },
});
Export default Example;
```

Thank you !

**Comment by pxue** [comment]
Seems like a problem with the lastest RN 0.43 and React 16 alpha with the new `prop-types` package. I have no solutions yet.

**Comment by pxue** [comment]
Seems like this line https://github.com/oblador/react-native-parallax/blob/master/ParallaxImage.js#L94 is now invalid in the latest RN version.
There's a validation check that only allows one key per transform.

**Comment by Kris4an7** [comment]
Would it work with React-native 0.42 ?

**Comment by kri-yor** [comment]
Hmm, I understand. I did have the error on the react-native 0.42.3, not the 43. I actually downgraded because of some dependency issues to 0.42.0 yesterday. Do you think it will work with that version or it's not that simple and just downgrade ?

**Comment by pxue** [comment]
I just upgraded from 0.41.1, So I'm not sure about 0.42.
I've forked and fixed it here: https://github.com/pxue/react-native-parallax
Feel free to point your package.json to it for now. I'll submit a PR

**Comment by kri-yor** [comment]
Will test it later. Thanks a lot !

**Comment by oky1** [comment]
Same Problem. Pxue thanks. Update please...

**Comment by bobmulder** [comment]
Having the same issue. The PR is still open, why not merged?

**Comment by dzpt** [comment]
Same issue,

**Comment by mgolkardev** [comment]
Hi

Please comment `extrapolate:  'clamp'`  in `\node_modules\react-native-parallax\ParallaxImage.js` line 94
or 
Move `extrapolate` to `scrollY.interpolate` like this

```
          translateY:   scrollY.interpolate({
            inputRange:   [offset - height, offset + WINDOW_HEIGHT + height],
            outputRange:  [-parallaxPadding, parallaxPadding],
            extrapolate:  'clamp',
          }),
```

Your problem will be resolved.

**Comment by MyTotoro** [comment]
@mgolkardev Can you submit a pr? It'd be great to get this in - don't want to steal your thunder!
