### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by kevin-bache** [oblador/react-native-parallax#3]
Any plans to port this to ES6?

**Comment by oblador** [comment]
By ES6 do you mean `class ... extends` etc? AFAIK this project is valid ES6 :-)

It will still be transpiled by babel in the end, so I'm curious how it affects you as user of this component.

**Comment by kevin-bache** [comment]
I'm having troubles with the mixins not working in ES6

**Comment by oblador** [comment]
@kevin-bache: Try [0.2.0](https://github.com/oblador/react-native-parallax/releases/tag/v0.2.0) that uses composition instead of mixin.
