### ISSUE TITLE
children.map is not a function

### ISSUE THREAD

**Issue by Zhangdroid** [oblador/react-native-parallax#4]
Hi, I was trying to run the basic example:

``` js
var Parallax = require('react-native-parallax');

var ParallaxView = React.createClass({
  render: function() {
    return (
      <Parallax.ScrollView>
        <Parallax.Image
          style={{ height: 200 }}
          overlayStyle={{ backgroundColor: 'rgba(0,0,0,0.3)'}}
          source={{ uri: 'http://loremflickr.com/640/480' }}
        >
          <Text>This is optional overlay content</Text>
        </Parallax.Image>
      </Parallax.ScrollView>
    );
  },
});
```

got this error:
![image](https://cloud.githubusercontent.com/assets/6471705/10731930/a958bf62-7c32-11e5-9a60-bb9c5a6b89dc.png)

but this [Example](https://github.com/oblador/react-native-parallax/blob/master/Example/index.js) is OK.

Use React-Native 0.13.1

**Comment by oblador** [comment]
Thanks for your bug report. This issue is now fixed in [0.2.1](https://github.com/oblador/react-native-parallax/releases/tag/v0.2.1).
