### ISSUE TITLE
How to use this with a ListView?

### ISSUE THREAD

**Issue by ygor** [oblador/react-native-parallax#5]
Hi, somehow using this as a row:

```
  <Parallax.ScrollView>
    <Parallax.Image
      style={{ height: 200 }}
      overlayStyle={{ backgroundColor: 'rgba(0,0,0,0.3)'}}
      source={{ uri: 'http://lorempixel.com/400/200/?' + movie.id }}
    />
  </Parallax.ScrollView>
```

does not seem to work. Any ideas how to use the parallax with a list?

**Comment by oblador** [comment]
Hi @ygor, 

ListView is not supported, but since ListView is basically a composition of ScrollView I don't think you need it in this case unless you have many rows (in which case parallax might not be very performant anyway).

What's your usecase?

**Comment by ygor** [comment]
Basically a list of images, similar to what the Timeline app does on iOS. Do you know what I can do to make it work in a Row (or, what is the reason for it not working in this context) ?

**Comment by oblador** [comment]
It's because the scrollview injects the scroll state to its children. But if you're not using the scrollview to scroll then nothing happens. You could try the [old mixin approach](https://github.com/oblador/react-native-parallax/blob/8992cffe149ca300e8d101f836be08cbfecf824a/README.md).

**Comment by ygor** [comment]
Yep the old approach worked, but I kept getting a strange bug when I scrolled a few rows to the bottom; the images started to get an increasing top-margin. And I was hoping this new version fixed that issue :)

**Comment by oblador** [comment]
That might be because it's not a direct descendant of the scrollview. The listview probably wraps all rows.
