### ISSUE TITLE
Nesting ?

### ISSUE THREAD

**Issue by achalghoum** [oblador/react-native-parallax#6]
Hello ,
Is it possible to have the parallax.image inside another element that is inside the parallax.scrollview ,
I have been trying to do this, but to no avail.
I would appreciate your help .

**Comment by oblador** [comment]
Hi, it's deprecated since it ES6 doesn't support mixins, but that approach still works. Read more in this [old README](https://github.com/oblador/react-native-parallax/blob/8992cffe149ca300e8d101f836be08cbfecf824a/README.md)
