### ISSUE TITLE
Invalid directory

### ISSUE THREAD

**Issue by nicklaunches** [oblador/react-native-parallax#7]
I made example from your page and Im getting error:

![screen shot 2015-12-05 at 11 57 43 pm](https://cloud.githubusercontent.com/assets/1409277/11612370/02e5bcf4-9bac-11e5-8a20-4133e259d28c.png)

![screen shot 2015-12-05 at 11 58 18 pm](https://cloud.githubusercontent.com/assets/1409277/11612371/15c7dee2-9bac-11e5-85fb-e3ab7b39ee39.png)

**Comment by oblador** [comment]
Did you npm install? If so it's probably a packager error, try restarting it.

**Comment by nicklaunches** [comment]
Problem was that npm installed it in wrong folder
