### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by nicklaunches** [oblador/react-native-parallax#9]
Is it possible to make infinite scroll for paralax?

Because ScrollView is child of ListView im trying to do

<Parallax.ScrollView
            style={styles.scrollView}
            imageNestLevel={3}
            onEndReached={this.onEndReached}>

But onEachReached not giving any callback. Thank you for help

**Comment by oblador** [comment]
@trane294: Is your question "does it work with ListView"? If so there's [an issue](https://github.com/oblador/react-native-parallax/issues/5) for that. Technically it _should_ work, but it seems like it's a bit buggy.

**Comment by nicklaunches** [comment]
@oblador: I tried it and it wasn't really working. Is it possible to you with Parallax.ScrollView with kinda callback like "onEndReached"?

**Comment by oblador** [comment]
Yep, but you have to implement the logic yourself. Basically just use `onScroll` in which you'll get how much the user has scrolled (or will with momentum scroll) and how large the content is. When the scroll + viewport height is as large as the content then you're at the end.

**Comment by nicklaunches** [comment]
@oblador: Okay. Ill try thank you!
